#!/usr/bin/python3

from sys import argv as a
import subprocess

hm = '''XELA usage:
xela [file] (flags)

XELA help:
-r  / -run           : run file
-c  / -compile       : compile file'''

if len(a) < 2:
    print(hm)
    exit(1)

if a[1] == '-h' or a[1] == '-help':
    print(hm)
else:

    otf = a[1].replace('.xela','.py')

    _str = ''
    state = 0
    c = ''
    be = 0

    with open(a[1],'r') as rf:
        rf = rf.readlines()
        with open(otf,'w') as wf:
            for i in rf:
                if be > 0:
                    wf.write('\t'*be)
                for w in i.split():
                    if w == 'load':
                        wf.write('import ')
                    elif w == '//' or w.startswith('//'):
                        wf.write('# ')
                    elif w == 'print':
                        wf.write('print( ')
                    elif w == 'endl':
                        wf.write(')')
                    elif w == 'for':
                        wf.write('for ')
                    elif w == 'range':
                        wf.write('range( ')
                    elif w == 'reverse':
                        wf.write('reversed( ')
                    elif w == 'to':
                        wf.write(', ')
                    elif w == 'endrg':
                        wf.write(')')
                    elif w == 'endrv':
                        wf.write('))')
                    elif w == 'while':
                        wf.write('while ')
                    elif w == 'T':
                        wf.write('True ')
                    elif w == 'F':
                        wf.write('False')
                    elif w == 'func':
                        wf.write('def ')
                    elif w == 'begin':
                        be += 1
                        wf.write(':')
                    elif w == 'not':
                        wf.write('not ')
                    elif w == 'end':
                        be = be - 1
                    elif w == 'if':
                        wf.write('if ')
                    elif w == 'elif':
                        wf.write('elif ')
                    elif w == 'else':
                        wf.write('else ')
                    elif w == 'ret':
                        wf.write('return ')
                    elif w == 'in':
                        wf.write('in ')
                    elif w == 'from':
                        wf.write('from ')
                    elif w == 'get':
                        wf.write('input( ')
                    elif w == 'endg':
                        wf.write(')')
                    else: wf.write(f'{w} ')
                wf.write('\n')

if len(a) >= 3:
    opt = a[2]
    if opt == '-r' or opt == '-run':
        subprocess.run(f'python3 {otf}',shell=True)
        subprocess.run(f'rm {otf}',shell=True)
    elif opt == '-c' or opt == '-compile':
        print('Compile success')
else:
    print('Compile success')
